import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";


import { Tajawal } from 'next/font/google'
 
// If loading a variable font, you don't need to specify the font weight
const tajawal = Tajawal({
  weight : "200",
  subsets : ["arabic"]
})


const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${tajawal.className} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
